#pragma once
#include <iostream>
#include <map>
#include <string>
#include <json/json.h>
#include <curl/curl.h>
#include <zip.h>
#include <chrono>
#include <thread>
#include <vector>
#include <fstream>
#include "Time.h"
#include "Console.h"
#include "VersionData.h"
#include "Settings.h"
#include "CommandList.h"
#include "ProgressBar.h"
#include "Commands.h"